language: ruby
rvm:
- 2.5.1
cache:
- bundler
- directories:
  - "/home/travis/.rvm/"
services:
- postgresql
before_script:
- cp config/database.yml config/database.yml.back
- cp config/database.yml.travis.yml config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rails test
after_success:
- cp config/database.yml config/database.yml.travis.yml
- mv config/database.yml.back config/database.yml
deploy:
  provider: heroku
  app:
    master: odin-facebook-hot-winter
  api_key:
    secure: hYOQkMyrinn1hHLuJ0qOZ18duTgt4e6/sSk0MOkvCvZuLGzubEPvLfz4sbqIghi2drftMKrcF9O/XnK/ohjzv65qCh/p/3QmTRF+H/IRMyu/3Z9IqBQgpMD2SnfTw/iS/DWk/7PjM9BbzdZqPjXmpFsd+FHEJP5de2cxfPBvM9VcaNRY+ZLqYi9Poa9ef6DD4Uj57sgmtypxZWzKOJj2VRl31Yx7biFcWX9eLCeDGoAiPF7IfZRFnySqzUT45nvqYB9ppmmVEZZ5N08CCnErNio43ARCk6RhBZDKMxxcxMBs8ItRzq8zWtgoj580vJicRvgm0U+S+LgvpKdkIslmz5BWSxWLs2srJiY4y1KzPKpY/nzswg2VVwJEol8nlaIPj1u5okwO41nhhGfd9mzqQAdmk+MjPxNzJ59UPgtFYXCqSPo91sToUqEH+ey/VJDnvyZfVqZ6lSSa/FUpOTRSLlsfvZuE84pQQ3VsZmlGx3bpYNmTAQr7oertNt7N/8h5cxltm0kLPxKR5G/raPZlMAhtIII9l6LgZe6ctnqg3DV4SalHNqSoPh4svt/IEefzuvBAs2F8D/cCpEBoDlLh6Vhc/vhV+UoSliLiJzqXZayPWztR5PFsp2VQa15EMAocGmAMW7ybdHQrwhHAO1DCajhmNnZFfo01P9+c+cOAWz8=
  run: rake db:migrate
notifications:
  slack:
    secure: TgcbUPzVGVy81nqEQ3Q4dGVwaTngsRNP04/pqIP3FK9gzx2ykv7omfNjlYSEZ1RbFaWM+m5mfftu8BeXiRbAtxjXBdOyE9/bfVBuF04Z1UFSVXmjWgNIZIo3CEQOXlbqwNGnHquZuU9NieRiaJnuiDy0LHDKDtDmgEuD6GU9vw+inqN7FkSvaP6zz1EWgOzLxg0bzzmLNmMk/gh7apAdmpce5tRKFQu4+yb/WmdHCAj+xIZDw2y1rVRhwDrF0RxjaWn8vMAzPGovC/qIV1Xj4dgWt7lzbv7OH8Lh50kQlpIp95QCzcSDadL/LrHh219vK/oRASr3Uq4EOlS/FTlqhVRFd6wIkojU1VjEck/BMl91yKu3CO9WkSYWXrG3LkBg/AZtZoKZk+Lwdp6nMGFTqgdwT1A+taqvqRooOWYq/GjKC4RS+IiukiYlU6FflgSCeGoJ2PoboDgu2pGj4YPitWu54cw62YCxgPR+Lfs3Czr8WO8EhTqDuwjwfz0HvpasM9BsAVDAbwMBEiIkU1xGSPPDEnqUjIXoqCQEGbHKtc7aqGQC7By6v7ovJ6F1WPQxNFdFkiNh5T/W97XNXnyeMS+VY16RBwsVR22ZM2SWUGVFqQweUDYXDYp86t6fygnr0ABwdeuijnPNvlcRle+I4Wa48D3JIkYXffZMtoye4nI=

# Rails master key env
env:
  secure: UowSf5oYMk/gUymhrY8rzYoO7nkdWDPL2thIc/IPLl6fi014nBJosrwy7LFrwKc1rKRIO/hIZEroZtZjxG8wR930EXle5CM18mSTa5iNlIlYcT19fbVHMB1D8PvXLHsZWSv9+5Zjkj3SEEL5NJUOx2z9SyVhDL4AfP3fRKR2AMy8tWoKPStDcXsM33ZOTL9pKh6Hy8MUtU3NE/1lwgfO6/poI/qHdGsq5zS/M/KHbdxJhv0mYOegmdlXedlMFMD8YueFFu8lghPXg4n+F+rFKJiRIvjmLq0/ysm9Tm6aEV/PuI/xkXOEaWlj4i4d3Is0y9Q9UhsmkqtiWPcLYgcxlcoQ9IGCzugueg1mOyhnyXpUjrQQzZh34qeJJtHVOdH7CJJhLp1iPbviP6NRNa7ibPJEBnFFH8hfiHSL20ZBFbwnvgwjoXzUPGcahjK2ROAlDwn5jzsRSPM42vMo9cDMzDGslmC6w41UiZUa6Jg66rwCxxkRJMYf67qs/rz/qbHyHMA6e40AJAvI+TEbJ/KTLNFUs6YiJtJFk/lxD/V+Qv8rF3qNFTO+mbVigfhEKTwwuiHyV4IGb0eizoI1fiNcziZPN6u/S2yfiJJfEMV+dhjkfxcF4xSRXxLu/QAHc3ihER0XIeh+HyISst55x0AG0PPrt/fQvng+212tk6Lmqhw=
