language: ruby
rvm:
- 2.5.1
cache:
- bundler
- directories:
  - "/home/travis/.rvm/"
services:
- postgresql
before_script:
- cp config/database.yml config/database.yml.back
- cp config/database.yml.travis.yml config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rails test
after_script:
- cp config/database.yml config/database.yml.travis.yml
- mv config/database.yml.back config/database.yml

deploy:
  provider: heroku
  api_key:
    secure: iBxVw1iJbz0H7JxhcGasx2P9L8Sc1oCpBSe7NPAXaEskko7MVOLmxFGFGXu85m1R6qQqMc7ctcGeRwg/y3rvYlc1b+1TmpmU75QTs35tRy1c+47fSFPAOK4BnGJEfuFbqwEXYqyZDChTzctABvmnvS99z73f+Fh7fxxaxLcZIfUN0QRCiXcNrBddm+0jJZevNsPpor5RgbuNqKbuTVMsOrH4VDHWUOLfeMOMFKfxYAJYO/Eb7Eq/t4buNWX74nm19h9Af8az/QUp1UQ7Dkr9521HqT+ehRIyFmeu5OYzJVOxncjfuR+ZLVkC0/NfTR93aIc3xvKlY/+4ssGU2DjnmEdGly6QdHexwD+VKW6hvrTYHxhchsf3Jysffh6hE5MizoYCGU2DUGBwMuc908EW2DQlF0eXwHUuLy1frumLR465gGFsDDQNMCOooDZS+5Ee938YQUPVua0TDg9DDq0KEnHEnoRHPCxUNhxEbcJv3W830uo70OxA4H1Of0jIGGRGNAO1J7sA/Z8FNy51iatIvIRfmzeVoSnT1U3Al0hXVFGbs/D53f0HTBwBMUcP/xhw4L/NxuEmMJuQP5zvTy9FfmHK7DbeXcC3OD8D8kj6Go4bE1gq3F5LtkLpo8foe3Q8Isb4ZUd8GXcYyksGGDVXrojj7WCWUjxOdt9ajQGMF1A=
  app: odin-facebook-hot-winter
  run: "rake db:migrate"

notifications:
  slack:
    secure: ldDvUNJo13YVszW1YYVXfCaEqiABinBkGYuzmLbLsuTQvgak6zAOs8Et2cILR1wqfO7iNhM0RJEW00joTD1au2/7ZI7+O21EF3Cl0dU5Pp0byY4ZS7nAv01hrW0drjQY3f8n+8ZsRcdodbSOd9nildw/KtTKbTVnRLlFY/sqw1a1fCAb9Cdseih0EpejLziZgv/M+H+T6loBeCocGkFCCfT7ylgngZtVyOu9AQiz1HzzbxoaS8nTVyU0d5yg0A9gci8pQ6Oj1ewKUB4h+D4bUUiem08nUxi8Qd8eDSatvk7uEWBvti5B9EryIkRS/n/04ryLr15Ffz3hTc6E+c+t1kN+VrHg1kCHS+Ro7pyVm1bVyv3OqINxtJMaVHtxcCHCpEY2xVIW6+JWqxxV8UU2tRs6F6tPwVedZmzNAgUmiD1YlVK35m/mQM1ToVsCx3Yns4bIALJNxn7B83KmwlHYK5ZAL6lKXgvu2wD/IENNfYGHEk/fvPF/Mt58pur1iO3UZ0pjrx/5rT4ZXIdg6gwTYbVuebVE5IsBbm0inwGulpuE6u986gbH9nS4YsMSVKhiYxfFpZvvWEisWi/AOwgA0mLc7EB0fgHcpldMqco3pswBUx0rFK9pkliEmdgGJ/osa/UiNGAg1tbHsvknNvnxLdy47jjYRyWADaI+ZAordks=