language: ruby
rvm:
- 2.5.1
cache:
- bundler
- directories:
  - "/home/travis/.rvm/"
services:
- postgresql
before_script:
- cp config/database.yml config/database.yml.back
- cp config/database.yml.travis.yml config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rails test
after_success:
- cp config/database.yml config/database.yml.travis.yml
- mv config/database.yml.back config/database.yml
deploy:
  provider: heroku
  app: odin-facebook-hot-winter
  api_key:
    secure: hYOQkMyrinn1hHLuJ0qOZ18duTgt4e6/sSk0MOkvCvZuLGzubEPvLfz4sbqIghi2drftMKrcF9O/XnK/ohjzv65qCh/p/3QmTRF+H/IRMyu/3Z9IqBQgpMD2SnfTw/iS/DWk/7PjM9BbzdZqPjXmpFsd+FHEJP5de2cxfPBvM9VcaNRY+ZLqYi9Poa9ef6DD4Uj57sgmtypxZWzKOJj2VRl31Yx7biFcWX9eLCeDGoAiPF7IfZRFnySqzUT45nvqYB9ppmmVEZZ5N08CCnErNio43ARCk6RhBZDKMxxcxMBs8ItRzq8zWtgoj580vJicRvgm0U+S+LgvpKdkIslmz5BWSxWLs2srJiY4y1KzPKpY/nzswg2VVwJEol8nlaIPj1u5okwO41nhhGfd9mzqQAdmk+MjPxNzJ59UPgtFYXCqSPo91sToUqEH+ey/VJDnvyZfVqZ6lSSa/FUpOTRSLlsfvZuE84pQQ3VsZmlGx3bpYNmTAQr7oertNt7N/8h5cxltm0kLPxKR5G/raPZlMAhtIII9l6LgZe6ctnqg3DV4SalHNqSoPh4svt/IEefzuvBAs2F8D/cCpEBoDlLh6Vhc/vhV+UoSliLiJzqXZayPWztR5PFsp2VQa15EMAocGmAMW7ybdHQrwhHAO1DCajhmNnZFfo01P9+c+cOAWz8=
  run: rake db:migrate
notifications:
  slack:
    secure: ldDvUNJo13YVszW1YYVXfCaEqiABinBkGYuzmLbLsuTQvgak6zAOs8Et2cILR1wqfO7iNhM0RJEW00joTD1au2/7ZI7+O21EF3Cl0dU5Pp0byY4ZS7nAv01hrW0drjQY3f8n+8ZsRcdodbSOd9nildw/KtTKbTVnRLlFY/sqw1a1fCAb9Cdseih0EpejLziZgv/M+H+T6loBeCocGkFCCfT7ylgngZtVyOu9AQiz1HzzbxoaS8nTVyU0d5yg0A9gci8pQ6Oj1ewKUB4h+D4bUUiem08nUxi8Qd8eDSatvk7uEWBvti5B9EryIkRS/n/04ryLr15Ffz3hTc6E+c+t1kN+VrHg1kCHS+Ro7pyVm1bVyv3OqINxtJMaVHtxcCHCpEY2xVIW6+JWqxxV8UU2tRs6F6tPwVedZmzNAgUmiD1YlVK35m/mQM1ToVsCx3Yns4bIALJNxn7B83KmwlHYK5ZAL6lKXgvu2wD/IENNfYGHEk/fvPF/Mt58pur1iO3UZ0pjrx/5rT4ZXIdg6gwTYbVuebVE5IsBbm0inwGulpuE6u986gbH9nS4YsMSVKhiYxfFpZvvWEisWi/AOwgA0mLc7EB0fgHcpldMqco3pswBUx0rFK9pkliEmdgGJ/osa/UiNGAg1tbHsvknNvnxLdy47jjYRyWADaI+ZAordks=
